### ISSUE TITLE
could you make a flatpak for cipher?

### ISSUE THREAD

**Issue by ghost** [arshubham/cipher#14]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for cipher?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by arshubham** [comment]
I was already planning to make a flatpak and a snap in about a week or so just to test out the waters with these containerized formats...

**Comment by altntowin** [comment]
oh good news, i hope to see the application soon on flatpak format

**Comment by arshubham** [comment]
I was able to build the flatpak locally. Just need to resolve some theme issues with gtk3.22 and appdata errors. Will try to submit on flathub as soon as possible.

**Comment by emarcelcom** [comment]
I like your app. Can we get this app on other distros than EOS?

**Comment by sahilarora3117** [comment]
This application is now available on flathub and can be installed from here
[Flathub](https://flathub.org/apps/details/com.github.arshubham.cipher)
