### ISSUE TITLE
Could you make it clear that this does not encrypt things?

### ISSUE THREAD

**Issue by retiform** [arshubham/cipher#15]
People using ElementaryOS are more likely to be new to Linux and less techy, so please note this can be easily reversed in the description.  It would be easy for someone who lacks crypto knowledge to confuse cipher with encryption.

**Comment by arshubham** [comment]
I will make the appropriate clarifications in the next version.

**Comment by arshubham** [comment]
Added to appdata in https://github.com/arshubham/cipher/commit/a02d7c72833126755b1a32876af1d23709eb5aac
