### ISSUE TITLE
Bugged display when selecting numbers of letters to shift to the right

### ISSUE THREAD

**Issue by NathanBnm** [arshubham/cipher#27]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/51804941-4c625780-2267-11e9-9edc-52515fd40c72.png)

**Comment by arshubham** [comment]
I am thinking of a redesign to the app. Will be fixed soon.

**Comment by arshubham** [comment]
@NathanBnm  I looked into fixing this however according to this issue https://gitlab.gnome.org/GNOME/gtk/issues/270 , it is an accessibility feature and won't be removed. So I can't do anything here. for Combobox. 
I can replace it with Spin Button if you like. 
![image](https://user-images.githubusercontent.com/14235191/51855508-5b0f4400-2325-11e9-9011-636073beb7c3.png)

**Comment by NathanBnm** [comment]
@arshubham yes Spin Button is definitely better :+1:  What do you think?

**Comment by NathanBnm** [comment]
Great!

@arshubham  I like it :+1:
