### ISSUE TITLE
Blurred icon in app view in AppCenter

### ISSUE THREAD

**Issue by NathanBnm** [arshubham/cipher#28]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/45366162/51804958-90edf300-2267-11e9-91bc-849683e83121.png)

**Comment by ryonakano** [comment]
I think the icon size of `data/images/com.github.arshubham.cipher.svg` is too small (48px x 48px). I would say replacing it with `data/images/icons/128/com.github.arshubham.cipher.svg` and publishing new release to AppCenter would fix this issue.

**Comment by arshubham** [comment]
Fixed in https://github.com/arshubham/cipher/commit/f11053591bdc50e601de150e83572d90429d286c
